import Link from 'next/link';
import {getGaps} from '@/lib/gaps';
import {getCapabilities} from '@/lib/capabilities';
export const dynamic='force-dynamic';
export default async function Gaps(){
 const caps=getCapabilities();let gaps:Awaited<ReturnType<typeof getGaps>>=[];let failed=false;
 try{gaps=await getGaps();}catch{failed=true;}
 return <main className="shell gap-page"><Link className="back-link" href="/">← Back to Disruption Desk</Link><span className="eyebrow">AN HONEST SOURCEBOOK</span><h1>What we don’t<br/><span>know yet.</span></h1><p>Abstentions become controlled coverage-gap records. We store no search text, names, booking references or IP addresses.</p><div className="status-strip"><span>{caps.mode}</span><span>{caps.backend} · {caps.gapWrites?'Sanity writes enabled':'Local-only gap storage'}</span></div><section className="rail-card"><h2>Known limits</h2><ul><li>Indian CAR Part IV Rev.4 and refund Part II Rev.3 (2026) are verified. Foreign-carrier compensation and individual baggage damages still need case-specific review.</li><li>Indian first-leg denied boarding and missed same-ticket cancellation connections are supported. Other connecting itineraries, universal claim deadlines and Switzerland require separate review.</li><li>Official court announcements are summaries; full judgment verification remains outstanding.</li><li>Only IndiGo and Delta contractual excerpts were verified.</li></ul></section><h2>Recent abstentions</h2>{failed?<p className="error" role="alert">Gap storage could not be read. No fallback records are shown.</p>:gaps.length?<div className="gap-list">{gaps.map(g=><article key={g._id}><span className="eyebrow">{g.category.replaceAll('_',' ')} · {g.regime.toUpperCase()}</span><p>{g.reason}</p><small>{g.createdAt} · {g.mode} · {g.backend}</small></article>)}</div>:<p>No recorded abstentions in this storage instance.</p>}<p className="legal-note">Local records do not persist across Vercel instances. Set a server-only Sanity write binding for durable gaps. Public gap documents contain only controlled classifications.</p></main>;
}
