'use client';
import {useState,useRef,useEffect} from 'react';
import Link from 'next/link';
import examples from '../../data/examples/questions.json';
import type {Scenario,Ruling,Source,Document} from '@/lib/types';
import type {getCapabilities} from '@/lib/capabilities';
type Capabilities=ReturnType<typeof getCapabilities>;
type ResponseData={ruling:Ruling;annotation:string|null;capabilities:Capabilities;gap?:{warning?:string;persisted:boolean}};
const regions=[['eu','EU / EEA*'],['uk','United Kingdom'],['in','India'],['us','United States'],['other','Elsewhere']];
const names:Record<string,string>={compensation:'Fixed compensation',meals_and_refreshments:'Meals & refreshments',communications:'Calls / messages',hotel_and_transport:'Overnight hotel & transport',refund_or_rerouting_choice:'Refund or rerouting choice',unused_ticket_refund:'Unused-ticket refund'};
const money=(amount:number,currency:string|null)=>currency?new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:2}).format(amount):String(amount);
function Icon({name='arrow'}:{name?:string}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{name==='plane'?<path d="m3 14 7-3V4c0-3 4-3 4 0v7l7 3v2l-7-1v4l3 2v1l-5-1-5 1v-1l3-2v-4l-7 1z"/>:name==='book'?<><path d="M12 5c-4-3-8-2-9-1v15c3-2 6-2 9 0 3-2 6-2 9 0V4c-3-1-6-1-9 1z"/><path d="M12 5v14"/></>:<path d="M5 12h14m-6-6 6 6-6 6"/>}</svg>}
export default function Desk({capabilities,sourceList,contentError}:{capabilities:Capabilities;sourceList:Source[];contentError:string|null}) {
 const [input,setInput]=useState<Scenario>(examples[0].input as Scenario);
 const [result,setResult]=useState<ResponseData|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [query,setQuery]=useState('');const [search,setSearch]=useState<{matches:Document[];examples:typeof examples;notice:string}|null>(null);const [searchBusy,setSearchBusy]=useState(false);
 const [drawer,setDrawer]=useState(false);const [activeExample,setActiveExample]=useState<string|null>(examples[0].id);const resultsRef=useRef<HTMLElement>(null);const drawerRef=useRef<HTMLElement>(null);const previousFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(!drawer)return;previousFocus.current=document.activeElement as HTMLElement;const panel=drawerRef.current;panel?.querySelector<HTMLButtonElement>('button')?.focus();function onKey(e:KeyboardEvent){if(e.key==='Escape')setDrawer(false);if(e.key==='Tab'&&panel){const focusables=panel.querySelectorAll<HTMLElement>('button,a[href]');const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}document.addEventListener('keydown',onKey);const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=prev;previousFocus.current?.focus();};},[drawer]);
 const field=<K extends keyof Scenario>(key:K,value:Scenario[K])=>{setInput(x=>({...x,[key]:value}));setActiveExample(null);setResult(null);};
 async function assess(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setResult(null);try{const response=await fetch('/api/ruling',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);requestAnimationFrame(()=>resultsRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}catch(e){setError(e instanceof Error?e.message:'The request failed.');}finally{setBusy(false);}}
 async function discover(e:React.FormEvent){e.preventDefault();setSearchBusy(true);setError('');try{const response=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSearch(data);}catch(e){setError(e instanceof Error?e.message:'Search failed.');}finally{setSearchBusy(false);}}
 function loadExample(example:typeof examples[number]){setInput(example.input as Scenario);setResult(null);setError('');setActiveExample(example.id);document.getElementById('flight-form')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const regionSelect=(label:string,key:'departure'|'arrival'|'carrier')=><label>{label}<select value={input[key]} onChange={e=>field(key,e.target.value as Scenario[typeof key])}>{regions.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>;
 const numberInput=(label:string,key:keyof Scenario,unit:string,max=100000)=><label>{label}<span className="input-unit"><input type="number" required min="0" max={max} value={input[key] as number} onChange={e=>field(key,Number(e.target.value))}/><span>{unit}</span></span></label>;
 return <>
  <header className="topbar"><Link href="/" className="brand"><span className="brand-mark"><Icon name="plane"/></span>Disruption<span className="brand-light">Desk</span></Link><nav><button onClick={()=>setDrawer(true)} className="nav-link">The sourcebook <span><Icon/></span></button><Link href="/gaps" className="nav-link">Coverage gaps</Link><span className="mode"><i/>{capabilities.mode.replace('_',' ')}</span></nav></header>
  <main className="shell">
   <section className="hero"><div className="eyebrow"><span className="tiny-line"/> A FLIGHT CHANGED. YOUR RIGHTS DIDN’T DISAPPEAR.</div><h1>Less turbulence.<br/><span>More clarity.</span></h1><div className="hero-bottom"><p>A cancelled flight. A missed day. A seat you never got.<br/>Check where you stand, with the rules and sources to back it up.</p><div className="hero-note"><span>01 — FACTS FIRST</span><p>Amounts calculated in code.<br/>Uncertainty kept in plain sight.</p></div></div></section>
   <div className="status-strip"><span><i className="status-dot"/>{capabilities.mode==='DETERMINISTIC'?'AI mode is off · structured rules, no model guesses':`${capabilities.mode} · agent retrieval + verified computation`}</span><span className={capabilities.backend==='LOCAL_SNAPSHOT'?'local-label':''}>{capabilities.backend==='LOCAL_SNAPSHOT'?'LOCAL CORPUS · Sanity not connected':'PUBLIC SANITY DATASET · live queries'}</span></div>
   {contentError&&<p role="alert" className="error">{contentError}</p>}
   <div className="workspace"><section className="form-panel" id="flight-form"><div className="section-head"><div><span className="eyebrow">THE FLIGHT FILE</span><h2>Tell us what happened.</h2></div><span className="file-number">DD / 001</span></div>
    <p className="form-intro">{activeExample?'Sample facts are loaded. Edit them to match your flight.':'Use the operating carrier and final-arrival delay.'} *EU here includes the EEA; Switzerland is outside this engine.</p>
    <form onSubmit={assess}>
     <fieldset><legend><span>01</span> The route</legend><div className="grid three">{regionSelect('Departure jurisdiction','departure')}{regionSelect('Arrival jurisdiction','arrival')}{regionSelect('Carrier licence','carrier')}</div><div className="grid three"><label>Operating airline<select value={input.airline} onChange={e=>field('airline',e.target.value)}>{['Unspecified','IndiGo','Air India','Air India Express','SpiceJet','Akasa Air','Ryanair','easyJet','Lufthansa','British Airways','Delta','United'].map(a=><option key={a}>{a}</option>)}</select></label><label>Flight date<input type="date" required value={input.flightDate} onChange={e=>field('flightDate',e.target.value)}/></label>{numberInput('Great-circle distance','distanceKm','km',25000)}</div></fieldset>
     <fieldset><legend><span>02</span> The disruption</legend><div className="event-options">{[['arrival_delay','Delayed'],['cancellation','Cancelled'],['denied_boarding','Denied boarding'],['care','Care'],['refund','Refund']].map(([v,n])=><button type="button" aria-pressed={input.trigger===v} key={v} className={input.trigger===v?'selected':''} onClick={()=>field('trigger',v as Scenario['trigger'])}>{n}</button>)}</div><div className="grid two">{numberInput(input.declinedTravelAndBenefits&&(input.departure==='us'||input.arrival==='us')?'Changed scheduled-arrival delay':'Final-arrival delay','arrivalDelayMinutes','min')}{numberInput('Departure delay / wait','departureDelayMinutes','min')}</div><div className="grid two"><label>Reported cause<select value={input.cause} onChange={e=>field('cause',e.target.value as Scenario['cause'])}>{[['operational','Airline operations'],['technical','Technical problem'],['weather','Weather'],['atc','Air traffic control'],['strike','Strike'],['unknown','Not known']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Carrier’s extraordinary-circumstances defense<select value={input.extraordinaryEvidence} onChange={e=>field('extraordinaryEvidence',e.target.value as Scenario['extraordinaryEvidence'])}><option value="not_proven">No proven defense</option><option value="unknown">Evidence not assessed</option><option value="proven">Proven, including reasonable measures</option></select></label></div><p className="hint">A cause label is not proof. If the airline’s evidence is disputed or unclear, choose “Evidence not assessed”.</p>
     {input.trigger==='cancellation'&&<div className="grid two">{numberInput('Cancellation notice before departure','noticeHours','hours')}</div>}
     {input.trigger==='denied_boarding'&&<><div className="grid two"><label>Reason for refusal<select value={input.deniedReason} onChange={e=>field('deniedReason',e.target.value as Scenario['deniedReason'])}>{['oversales','security','health','documentation','other'].map(r=><option key={r}>{r}</option>)}</select></label>{numberInput('Aircraft passenger seats','aircraftSeats','seats',1000)}</div><div className="grid two">{numberInput('Fare to first stopover / destination','fare','',1000000)}<label>Fare currency<select value={input.fareCurrency} onChange={e=>field('fareCurrency',e.target.value as Scenario['fareCurrency'])}>{['USD','EUR','GBP','INR'].map(c=><option key={c}>{c}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={input.involuntary} onChange={e=>field('involuntary',e.target.checked)}/>I was denied boarding against my will.</label></>}
     <label className="check"><input type="checkbox" checked={input.reroutingOffered} onChange={e=>field('reroutingOffered',e.target.checked)}/>The airline offered alternative transport.</label>
     {input.reroutingOffered&&<div className="grid two">{numberInput('Offered transport’s scheduled arrival delay','reroutedArrivalDelayMinutes','min')}{numberInput('Offered departure earlier than original','reroutedDepartureEarlyMinutes','min')}</div>}
     <label className="check"><input type="checkbox" checked={input.overnight} onChange={e=>field('overnight',e.target.checked)}/>An overnight stay became necessary while waiting.</label><label className="check"><input type="checkbox" checked={input.declinedTravelAndBenefits} onChange={e=>field('declinedTravelAndBenefits',e.target.checked)}/>I declined travel, rerouting, vouchers and alternative benefits.</label></fieldset>
     <details className="confirmations" open><summary>Confirm the conditions <span>5 checks</span></summary><label className="check"><input type="checkbox" checked={input.confirmedBooking} onChange={e=>field('confirmedBooking',e.target.checked)}/>I held a confirmed reservation.</label><label className="check"><input type="checkbox" checked={input.checkedInOnTime} onChange={e=>field('checkedInOnTime',e.target.checked)}/>I met the airline’s check-in / boarding deadlines.</label><label className="check"><input type="checkbox" checked={input.singleFlight} onChange={e=>field('singleFlight',e.target.checked)}/>This concerns one scheduled flight, not a connecting itinerary.</label><label className="check"><input type="checkbox" checked={input.eligibleTicketAndAircraft} onChange={e=>field('eligibleTicketAndAircraft',e.target.checked)}/>I used a public fare or rewards ticket on a fixed-wing passenger aircraft.</label><label className="check"><input type="checkbox" checked={input.receivedBenefitsAbroad} onChange={e=>field('receivedBenefitsAbroad',e.target.checked)}/>I already received compensation and assistance abroad.</label></details>
     <button className="primary-button" disabled={busy||!!contentError} type="submit">{busy?'Checking the sourcebook…':'Check my rights'}<Icon/></button><p className="legal-note">Information, not legal advice. Conditional on your facts. No personal details required.</p>
    </form></section>
    <aside className="rail"><div className="rail-card"><span className="eyebrow">HOW THE DESK WORKS</span><h3>Evidence.<br/>Then an answer.</h3><ol><li><span>01</span><div><strong>Find the applicable rules</strong><p>Route, carrier and disruption determine which protections apply.</p></div></li><li><span>02</span><div><strong>Check every condition</strong><p>Notice, delay, cause and offered transport change the outcome.</p></div></li><li><span>03</span><div><strong>Show the working</strong><p>Computed amounts. Linked sources. A clear “not determined” when needed.</p></div></li></ol><button onClick={()=>setDrawer(true)} className="text-button">Explore the sourcebook <Icon name="book"/></button></div>
    <div className="coverage-card"><span className="eyebrow">CURRENT COVERAGE</span><div className="coverage-row"><span>European Union</span><span>EU261</span></div><div className="coverage-row"><span>United Kingdom</span><span>UK261</span></div><div className="coverage-row"><span>United States</span><span>Federal rules</span></div><div className="coverage-row muted"><span>India</span><span>Verification gap</span></div><p>Indian statutory entitlements, connecting journeys and baggage are not determined. Court coverage uses labeled official summaries.</p></div>
    <div className="example-list"><span className="eyebrow">START WITH A FLIGHT FILE</span>{[examples[0],examples[2],examples[4],examples[6]].map(e=><button key={e.id} onClick={()=>loadExample(e)}><span><strong>{e.question}</strong><small>PRECOMPUTED EXAMPLE · LOAD FACTS</small></span><span><Icon/></span></button>)}</div>
    </aside></div>
   {error&&<p role="alert" className="error">{error}</p>}
   <section ref={resultsRef} className="result-section" aria-live="polite">{result&&<><div className="section-head"><div><span className="eyebrow">THE SOURCED RULING</span><h2>{result.ruling.status==='abstain'?'We can’t determine this yet.':result.ruling.status==='partial'?'Some answers. Some open questions.':'Here’s where you stand.'}</h2></div><span className="result-status">{result.ruling.status.toUpperCase()}</span></div>{result.annotation&&<p>{result.annotation}</p>}<div className="finding-grid">{result.ruling.findings.map((f,i)=><article className="finding" key={`${f.regime}-${i}`}><div className="finding-top"><strong>{f.regime.toUpperCase()}</strong><span>{f.status==='abstain'?'REVIEW NEEDED':'CONDITIONS ASSESSED'}</span></div><div className="award">{f.amount===null?(f.status==='assessed'?'Care / refund rights':'Not determined'):f.amount===0?'No fixed award':money(f.amount,f.currency)}</div><p className="award-caption">{f.amountLabel}</p><div className="entitlements">{f.entitlements.map(ent=><span key={ent}>{names[ent]||ent}</span>)}</div>{f.met.length>0&&<details open><summary>Conditions met</summary><ul>{f.met.map((x,j)=><li key={j}>{x}</li>)}</ul></details>}{f.unmet.length>0&&<details open><summary>Conditions not met</summary><ul>{f.unmet.map((x,j)=><li key={j}>{x}</li>)}</ul></details>}{f.uncertainties.map((u,j)=><p className="uncertainty" key={j}>{u}</p>)}<div className="finding-citations">{result.ruling.sources.filter(s=>f.sourceIds.includes(s._id)).map(s=><a href={s.url} key={s._id} target="_blank" rel="noreferrer">T{s.authorityTier} · {s.title} <Icon/></a>)}</div></article>)}</div>{result.ruling.conflicts.map((c,i)=><article key={i} className="conflict"><span className="eyebrow">SOURCES IN TENSION</span><h3>{c.topic}</h3><div className="grid two">{[c.left,c.right].map((x,j)=><div key={j}><a href={x.source.url} target="_blank" rel="noreferrer">Tier {x.source.authorityTier} · {x.source.publisher} <Icon/></a><p>{x.claim}</p></div>)}</div><strong>{c.resolution}</strong></article>)}<p className="legal-note">{result.ruling.notice}</p>{result.gap?.warning&&<p className="hint">{result.gap.warning}</p>}</>}</section>
   <section className="search-section"><div><span className="eyebrow">LOOK THROUGH THE SOURCEBOOK</span><h2>Have a question instead?</h2><p>Search rules and official summaries, or find a labeled example.<br/>For a ruling on your own flight, use the form above.</p></div><form onSubmit={discover}><label className="sr-only" htmlFor="question">Search the sourcebook</label><div className="search-input"><input id="question" type="search" required minLength={3} maxLength={400} placeholder="Try ‘weather’, ‘refund’ or ‘denied boarding’" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={searchBusy} aria-label="Search sourcebook">{searchBusy?'…':<Icon/>}</button></div><span className="hint">{capabilities.mode==='DETERMINISTIC'?'Keyword search · AI mode is off':'Keyword discovery · use the structured form for agent adjudication'}</span></form></section>
   {search&&<section className="search-results"><p className="hint">{search.notice}</p>{!search.matches.length&&!search.examples.length&&<p>No match. This question is a coverage gap, not evidence of no rights.</p>}{search.matches.map(d=><article key={d._id}><span className="eyebrow">{d._type}</span><h3>{String('title' in d?d.title:'Structured cause stance')}</h3><p>{String('paraphrase' in d?d.paraphrase:'holding' in d?d.holding:'summary' in d?d.summary:'')}</p></article>)}{search.examples.map(e=><button key={e.id} className="example-search" onClick={()=>loadExample(e)}>{e.question}<small>PRECOMPUTED · LOAD SAMPLE FACTS</small></button>)}</section>}
   <footer><span className="brand">Disruption<span className="brand-light">Desk</span></span><p>A little less uncertainty at the gate.</p><span>DEV × SANITY CHALLENGE · PATH ONE</span></footer>
  </main>
  {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><aside ref={drawerRef} className="source-drawer" role="dialog" aria-modal="true" aria-labelledby="source-title" onClick={e=>e.stopPropagation()}><div className="section-head"><h2 id="source-title">The sourcebook</h2><button onClick={()=>setDrawer(false)} className="close-button" aria-label="Close sourcebook">×</button></div><p>Primary rules first. Official guidance next. Court summaries and carrier terms are labeled.</p><div className="tier-key">1 Law · 2 Regulator · 3 Court · 4 Airline · 5 Commercial</div>{sourceList.map(s=><article key={s._id}><span className="eyebrow">TIER {s.authorityTier} · {s.publisher}</span><h3><a href={s.url} target="_blank" rel="noreferrer">{s.title} <Icon/></a></h3><p>{s.licenseNote}</p><small>Retrieved {s.retrievedAt.slice(0,10)}</small></article>)}<p className="hint">{capabilities.backend==='LOCAL_SNAPSHOT'?'These are local prepared documents. They have not been published to Sanity.':'Source metadata is read from the configured public Sanity dataset.'}</p></aside></div>}
 </>;
}
